# Generated by Django 5.0.7 on 2024-07-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=8)),
                ('range', models.IntegerField()),
                ('ocupado', models.BooleanField()),
                ('descricacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anos', models.ManyToManyField(related_name='calendarios', to='calendario.ano')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.ManyToManyField(related_name='dias', to='calendario.horas')),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.ManyToManyField(related_name='meses', to='calendario.dia')),
            ],
        ),
        migrations.AddField(
            model_name='ano',
            name='meses',
            field=models.ManyToManyField(related_name='anos', to='calendario.mes'),
        ),
    ]
