# Generated by Django 5.0.7 on 2024-07-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='anos',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='mes',
            name='dias',
        ),
        migrations.DeleteModel(
            name='Ano',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
    ]
