# Generated by Django 5.0.7 on 2024-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_atividades_obs'),
        ('calendario', '0004_rename_descricacao_calendario_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='descricao',
        ),
        migrations.AddField(
            model_name='calendario',
            name='atividades',
            field=models.ManyToManyField(related_name='calendarios', to='atividades.atividades'),
        ),
    ]
