# Generated by Django 5.0.7 on 2024-07-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0007_remove_calendario_atividades_calendario_atividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
