# Generated by Django 5.0.7 on 2024-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0008_alter_calendario_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
