# Generated by Django 5.0.7 on 2024-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0009_calendario_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
