# Generated by Django 5.0.7 on 2024-07-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inst', models.CharField(max_length=33)),
                ('imagem', models.ImageField(blank=True, upload_to='intituicao/%Y/%m/%d')),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=12)),
                ('contato', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=30)),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequencia', models.IntegerField()),
                ('data_final_seq', models.DateTimeField()),
                ('intituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='atividades.instituicao')),
                ('tipo_atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo', to='atividades.tipoatividade')),
            ],
        ),
    ]
