# Generated by Django 5.0.7 on 2024-07-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
