# Generated by Django 5.0.7 on 2024-07-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_instituicao_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
