# Generated by Django 5.0.7 on 2024-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_instituicao_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='contato',
            field=models.CharField(max_length=35),
        ),
    ]
