# Generated by Django 5.0.7 on 2024-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_alter_instituicao_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='valor_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
