# Generated by Django 5.0.7 on 2024-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_alter_instituicao_valor_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.ImageField(blank='True', null='True', upload_to='intituicao/%Y/%m/%d'),
        ),
    ]
