# Generated by Django 5.0.7 on 2024-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_alter_instituicao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
