# Generated by Django 5.0.7 on 2024-07-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_atividades_obs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='intituicao',
            new_name='instituicao',
        ),
    ]
