# Generated by Django 5.0.7 on 2024-07-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0011_delete_atividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('valor_padrao', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seq_diario', models.BooleanField()),
                ('seq_semanal', models.BooleanField()),
                ('seq_mensal', models.BooleanField()),
                ('seq_none', models.BooleanField()),
                ('data_final_seq', models.DateTimeField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='atividades.instituicao')),
                ('tipo_atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo', to='atividades.tipoatividade')),
            ],
        ),
    ]
