# Generated by Django 5.0.7 on 2024-07-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0012_atividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='seq_diario',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='seq_mensal',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='seq_none',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='seq_semanal',
        ),
        migrations.AddField(
            model_name='atividades',
            name='sequencia',
            field=models.CharField(choices=[('1', 'dia'), ('2', 'semana'), ('3', 'mes'), ('4', 'none')], max_length=1, null=True),
        ),
    ]
