# Generated by Django 5.0.7 on 2024-07-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0013_remove_atividades_seq_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='data_final_seq',
            field=models.DateField(),
        ),
    ]
