# Generated by Django 5.0.7 on 2024-07-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0015_alter_atividades_sequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='data_final_seq',
            field=models.DateField(null=True),
        ),
    ]
