# Generated by Django 5.0.7 on 2024-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0016_alter_atividades_data_final_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='data_final_seq',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='sequencia',
            field=models.CharField(blank=True, choices=[('1', 'dia'), ('2', 'semana'), ('3', 'mes')], max_length=1, null=True),
        ),
    ]
