# Generated by Django 5.0.7 on 2024-07-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0018_alter_atividades_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
