# Generated by Django 5.0.7 on 2024-07-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0019_alter_atividades_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='entrada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='saida',
            field=models.IntegerField(),
        ),
    ]
