# Generated by Django 5.0.7 on 2024-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0023_alter_atividades_sequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='sequencia',
            field=models.CharField(blank=True, choices=[(1, 'Dias Úteis'), (2, 'Semanal'), (3, 'Mensal')], max_length=1, null=True),
        ),
    ]
