# Generated by Django 5.0.7 on 2024-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0025_remove_atividades_valor_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='sequencia',
            field=models.CharField(blank=True, choices=[('', 'Sem Repetição'), ('1', 'Dias Úteis'), ('2', 'Semanal'), ('3', 'Mensal')], max_length=1, null=True),
        ),
    ]
