# Generated by Django 5.0.7 on 2024-08-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0026_atividades_cod_alter_atividades_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='id_vir',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
