# Generated by Django 5.0.7 on 2024-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0027_atividades_id_vir'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='nome_curto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome_inst',
            field=models.CharField(max_length=50),
        ),
    ]
