# Generated by Django 5.0.7 on 2024-08-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0028_instituicao_nome_curto_alter_instituicao_nome_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='nome_curto',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
