# Generated by Django 5.0.7 on 2024-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0029_alter_instituicao_nome_curto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='valor_padrao',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
