# Generated by Django 5.0.7 on 2024-08-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0030_alter_instituicao_valor_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='valor_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
