# Generated by Django 5.0.7 on 2024-08-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0032_alter_instituicao_valor_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='valor_padrao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
