# Generated by Django 5.0.7 on 2024-08-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0033_alter_instituicao_valor_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='valor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
