# Generated by Django 5.0.7 on 2024-08-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0034_alter_atividades_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='instituicao/%Y/%m/%d'),
        ),
    ]
