# Generated by Django 5.0.7 on 2024-08-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0037_remove_tipoatividade_horas_tipoatividade_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
    ]
