# Generated by Django 5.0.7 on 2024-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0038_alter_tipoatividade_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='valor_padrao',
            new_name='valor_fixo',
        ),
        migrations.AddField(
            model_name='atividades',
            name='fixo_mensal_ativ',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='fixo_mensal_inst',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
