# Generated by Django 5.0.7 on 2024-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0039_rename_valor_padrao_instituicao_valor_fixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='fixo_mensal_ativ',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
