# Generated by Django 5.0.7 on 2024-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0040_alter_atividades_fixo_mensal_ativ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='fixo_mensal_inst',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
