# Generated by Django 5.0.7 on 2024-08-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0041_alter_instituicao_fixo_mensal_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='cod_fixo_ativ',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='cod_fixo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='fixo_mensal_ativ',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='fixo_mensal_inst',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
