# Generated by Django 5.0.7 on 2024-08-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0044_alter_atividades_seq_pesonalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='seq_pesonalizada',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
