# Generated by Django 5.0.7 on 2024-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0047_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='nome_tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
