# Generated by Django 5.0.7 on 2024-08-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0049_alter_tipoatividade_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='atividades.categoria'),
        ),
    ]
