# Generated by Django 5.0.7 on 2024-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0050_alter_tipoatividade_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_sono', models.IntegerField()),
                ('tipo_grafico', models.CharField(max_length=10)),
            ],
        ),
    ]
