# Generated by Django 5.0.7 on 2024-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0051_preferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='hora_envio_tarefas',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
