# Generated by Django 5.0.7 on 2024-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0052_preferencias_hora_envio_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='inicio_semana',
            field=models.CharField(blank=True, choices=[(0, 'Segunda-Feira'), (1, 'Domingo'), (2, 'Sábado'), (3, 'Sexta-Feira'), (4, 'Quinta-Feira'), (5, 'Quarta-Feira'), (6, 'Terça-Feira')], max_length=15, null=True),
        ),
    ]
