# Generated by Django 5.0.7 on 2024-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0055_alter_preferencias_tipo_grafico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='horas_sono',
            field=models.IntegerField(default=8),
        ),
    ]
