# Generated by Django 5.0.7 on 2024-09-10 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0056_alter_preferencias_horas_sono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='hora_envio_tarefas',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='inicio_semana',
            field=models.CharField(choices=[(0, 'Segunda-Feira'), (1, 'Domingo'), (2, 'Sábado'), (3, 'Sexta-Feira'), (4, 'Quinta-Feira'), (5, 'Quarta-Feira'), (6, 'Terça-Feira')], default='Domingo', max_length=15),
        ),
    ]
